In [14]:
import numpy as np

def sub_box(ar, i, j):
    a = list(ar[i * 3:i * 3 + 3, j * 3:j * 3 + 3].flatten())
    b = check_3_ar(a)
    if b == True: return f'Box True'
    return f'Box False'
    

def sub_col(ar,n):
    # ar = ar[:,n]
    b = check_3_ar(ar[:,n])
    if b == True: return f'Col True'
    return f'Col False'

def sub_row(ar,n):
    # ar = ar[n,:]
    b = check_3_ar(ar[n,:])
    if b == True: return f'Row True'
    return f'Row False'

# correct
array = [
    [1, 4, 5, 3, 2, 7, 6, 9, 8],
    [8, 3, 9, 6, 5, 4, 1, 2, 7],
    [6, 7, 2, 9, 1, 8, 5, 4, 3],
    [4, 9, 6, 1, 8, 5, 3, 7, 2],
    [2, 1, 8, 4, 7, 3, 9, 5, 6],
    [7, 5, 3, 2, 9, 6, 4, 8, 1],
    [3, 6, 7, 5, 4, 2, 8, 1, 9],
    [9, 8, 4, 7, 6, 1, 2, 3, 5],
    [5, 2, 1, 8, 3, 9, 7, 6, 4]
]

corr = np.array(array) 

# -------------------------------

bbb = np.random.randint(10, size=(9, 9))
# print(bb)

def check_3_ar(ar):
    ar = sorted(list(ar))
    a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
    return ar == a

def auto_check_9(ar):
    k = 0
    for i in range(3):
        for j in range(3):
            print(i, j)
            b = sub_box(ar, i, j)
            c = sub_col(ar, k)
            d = sub_row(ar, k)
            print(b)
            print(c)
            print(d)
            k += 1
        
    
if __name__ == '__main__':
    print(corr)
    auto_check_9(corr)


[[1 4 5 3 2 7 6 9 8]
 [8 3 9 6 5 4 1 2 7]
 [6 7 2 9 1 8 5 4 3]
 [4 9 6 1 8 5 3 7 2]
 [2 1 8 4 7 3 9 5 6]
 [7 5 3 2 9 6 4 8 1]
 [3 6 7 5 4 2 8 1 9]
 [9 8 4 7 6 1 2 3 5]
 [5 2 1 8 3 9 7 6 4]]
0 0
Box True
Col True
Row True
0 1
Box True
Col True
Row True
0 2
Box True
Col True
Row True
1 0
Box True
Col True
Row True
1 1
Box True
Col True
Row True
1 2
Box True
Col True
Row True
2 0
Box True
Col True
Row True
2 1
Box True
Col True
Row True
2 2
Box True
Col True
Row True
