In [114]:
import numpy as np


# correct

array = [
    [1, 4, 5, 3, 2, 7, 6, 9, 8],
    [8, 3, 9, 6, 5, 4, 1, 2, 7],
    [6, 7, 2, 9, 1, 8, 5, 4, 3],
    [4, 9, 6, 1, 8, 5, 3, 7, 2],
    [2, 1, 8, 4, 7, 3, 9, 5, 6],
    [7, 5, 3, 2, 9, 6, 4, 8, 1],
    [3, 6, 7, 5, 4, 2, 8, 1, 9],
    [9, 8, 4, 7, 6, 1, 2, 3, 5],
    [5, 2, 1, 8, 3, 9, 7, 6, 4]
]

# test
# array = [
#     [1, 0, 0, 0, 0, 0, 0, 0, 0],
#     [0, 2, 0, 0, 0, 0, 0, 0, 0],
#     [0, 0, 0, 0, 0, 0, 0, 0, 0],
#     [4, 0, 0, 0, 0, 0, 0, 0, 0],
#     [5, 0, 0, 0, 0, 0, 0, 0, 0],
#     [6, 0, 0, 0, 0, 0, 0, 0, 0],
#     [7, 0, 0, 0, 0, 0, 0, 0, 0],
#     [8, 0, 0, 0, 0, 0, 0, 0, 0],
#     [9, 0, 0, 0, 0, 0, 0, 0, 0]
# ]

#easy
easy_array = [
    [1, 0, 6, 0, 7, 8, 0, 3, 0],
    [0, 5, 7, 3, 4, 9, 0, 6, 2],
    [2, 9, 3, 6, 0, 5, 0, 0, 7],
    [0, 0, 0, 8, 0, 1, 6, 0, 4],
    [4, 6, 1, 0, 0, 0, 2, 8, 9],
    [5, 8, 0, 0, 6, 4, 3, 0, 0],
    [7, 3, 4, 1, 9, 6, 5, 0, 8],
    [6, 1, 8, 7, 0, 2, 4, 9, 3],
    [0, 0, 0, 0, 8, 0, 0, 1, 0]
]

easy_array = np.array(easy_array) 
corr = np.array(array)

# -------------------------------

bbb = np.random.randint(10, size=(9, 9))
# print(bb)

print(corr)


[[1 4 5 3 2 7 6 9 8]
 [8 3 9 6 5 4 1 2 7]
 [6 7 2 9 1 8 5 4 3]
 [4 9 6 1 8 5 3 7 2]
 [2 1 8 4 7 3 9 5 6]
 [7 5 3 2 9 6 4 8 1]
 [3 6 7 5 4 2 8 1 9]
 [9 8 4 7 6 1 2 3 5]
 [5 2 1 8 3 9 7 6 4]]


In [53]:
# _____________________ sudoku checker

def sub_box(ar, i, j):
    a = list(ar[i * 3:i * 3 + 3, j * 3:j * 3 + 3].flatten())
    b = check_3_ar(a)
    if b == True: return f'Box True'
    return f'Box False'

def sub_col(ar,n):
    # ar = ar[:,n]
    b = check_3_ar(ar[:,n])
    if b == True: return f'Col True'
    return f'Col False'

def sub_row(ar,n):
    # ar = ar[n,:]
    b = check_3_ar(ar[n,:])
    if b == True: return f'Row True'
    return f'Row False'

def check_3_ar(ar):
    ar = sorted(list(ar))
    a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
    return ar == a

def auto_check_9(ar):
    a = {}
    k = 0
    for i in range(3):
        for j in range(3):
            print(i, j)
            b = sub_box(ar, i, j)
            a.update({b})
            c = sub_col(ar, k)
            a.update({c})
            d = sub_row(ar, k)
            a.update({d})
            print(a)
            print(b)
            print(c)
            print(d)
            k += 1
    if b == f'Box True' and c == f'Col True' and d == f'Row True': 
        print('True')
        return True
    else: 
        print('False')
        return False

            

In [17]:
def auto_check_9(ar):
    aa = {'Col True', 'Row True', 'Box True'}
    a = set()
    k = 0
    for i in range(3):
        for j in range(3):
            print(i, j)
            b = sub_box(ar, i, j)
            a.add(b)
            c = sub_col(ar, k)
            a.add(c)
            d = sub_row(ar, k)
            a.add(d)
            print(a)
            # print(b)
            # print(c)
            # print(d)
            k += 1
    print(f'auto check 9 finished')
    if a == aa: 
        print('True')
        return True
    else: 
        print('False')
        return False
# print(easy_array)
# auto_check_9(easy_array)


In [2]:
# _____________________ role of sudoku   

# l = 0 ; m = 0
# for k in range(9):
#     for i in range(3):
#         for j in range(3):
#             print(f'{i + m }:{j + l}')
#     l+=3
#     if l > 6: l = 0; m += 3

# 0:0 0:1 0:2 1:0 1:1 1:2 2:0 2:1 2:2
# 0:3 0:4 0:5 1:3 1:4 1:5 2:3 2:4 2:5
# 0:6 0:7 0:8 1:6 1:7 1:8 2:6 2:7 2:8
# 3:0 3:1 3:2 4:0 4:1 4:2 5:0 5:1 5:2
# 3:3 3:4 3:5 4:3 4:4 4:5 5:3 5:4 5:5
# 3:6 3:7 3:8 4:6 4:7 4:8 5:6 5:7 5:8
# 6:0 6:1 6:2 7:0 7:1 7:2 8:0 8:1 8:2
    
# pattern of check sub-box
# [0:3,0:3] [0:3,3:6] [0:3,6:9] 
# [3:6,0:3] [3:6,3:6] [3:6,6:9] 
# [6:9,0:3] [6:9,3:6] [6:9,6:9]

sb_0 = [0,0,0,3,3,3,6,6,6]
sb_1 = [3,3,3,6,6,6,9,9,9]
sb_2 = [0,3,6,0,3,6,0,3,6]
sb_3 = [3,6,9,3,6,9,3,6,9]

def possible_check(ar,i,j,k,value):
    
    print(f'checking {i} {j} {value}')
    c = {1, 2, 3, 4, 5, 6, 7, 8, 9}
    # print(list(ar[i,:]))
    # print(list(ar[:,j]))
    # print(list(ar[sb_0[k]:sb_1[k], sb_2[k]:sb_3[k]].flatten()))
    if value == 0: 
        # print(ar)
        subrow = set(ar[i,:])
        # print(subrow) 
        subcol = set(ar[:,j])
        # print(subcol)
        # subbox = set(ar[i * 3:i * 3 + 3, j * 3:j * 3 + 3].flatten())
        subbox = set(ar[sb_0[k]:sb_1[k], sb_2[k]:sb_3[k]].flatten())
        # print(subbox)
        a = subrow.union(subcol,subbox)
        a = c - a
        print(f'a = {a}')
        if len(a) == 1:
            ar[i,j] = list(a)[0]
            print(f'ar[{i},{j}] = {list(a)[0]}')
            print(ar)
            # print(a)

def main(ar):
    arr = ar.copy()
    print(ar)
    b = 0
    while True:
        l = 0 ; m = 0 ; a = 0
        for k in range(9):
            for i in range(3):
                for j in range(3):
                    possible_check(arr, i+m, j+l, k, arr[i+m, j+l])
            l+=3
            if l > 6: l = 0; m += 3
        a += 1 ; b+=1 
        print(ar, end='\n\n')
        print(arr)
        print(f'possible_check finished {b} times')
        if auto_check_9(arr) : 
            print('this sudoku done!')
            break


if __name__ == '__main__':
    import time
    start_time = time.time()
    main(easy_array)
    finished_time = time.time()
    print(f'time = {finished_time - start_time} sec')

NameError: name 'easy_array' is not defined