In [127]:
import numpy as np

# np.random.seed(0)

k = (9,9)
aaa = np.zeros(k, dtype=int)
# a[0,0] = 1
# a[0,1] = 2
k = 1
for i in range(9):
    for j in range(9):
        aaa[i,j] = k
        k += 1
        if k > 9:
            k = 1
# print(aaa)
def sub_box(ar):
    # print(ar)
    s = int(input("Enter the : "))
    return ar[s-3:s,s-3:s]

def sub_col(ar):
    # print(ar)
    s = int(input("Enter the : "))
    # return ar[0:1,1]
    return ar[:,s]

def sub_row(ar):
    # print(ar)
    s = int(input("Enter the : "))
    # return ar[0:1,1]
    return ar[s,:]

b = np.array([[1,2,3],[4,5,6],[7,8,9]])
bb = np.array([[1,2,9],[4,5,6],[7,8,3]])
bbb = np.random.randint(10, size=(9, 9))
# print(bbb)

def check_3_ar(ar):q
    a = [1,2,3,4,5,6,7,8,9]
    for i in range(9):
        if ar[i] in a:
            a.remove(ar[i])
        else:
            return False
    if len(a) == 0: return True
    else: return False

def check_3_subbox(ar):
    print(ar)
    ar = ar.flatten()
    check_3_ar(ar)
    

def check_3_row(ar):
    print(ar)
    check_3_ar(ar)
    

def check_3_col(ar):
    print(ar)
    check_3_ar(ar)
    
if __name__ == '__main__':
    print(bbb)
    # ss = sub_box(aaa)
    # aaaa = sub_row(aaa)
    # aaaaa = sub_col(aaa)
    # print(sub_row(aaa))
    # print(sub_col(aaa))
    # print(check_3_subbox(ss))
    # print(check_3_subbox(b))
    # print(check_3_subbox(bb))
    # print(check_3_row(aaaa))
    # print(check_3_col(aaaaa))

    

# print(a.shape)
# print(a.dtype)
# print(a.ndim)
# print()

[[3 5 7 2 7 1 6 5 0]
 [0 3 1 9 9 6 6 7 8]
 [8 7 0 8 6 8 9 8 3]
 [6 1 7 4 9 2 0 8 2]
 [7 8 4 4 1 7 6 9 4]
 [1 5 9 7 1 3 5 7 3]
 [6 6 7 9 1 9 6 0 3]
 [8 4 1 4 5 0 3 1 4]
 [4 4 0 0 8 4 6 9 3]]
[[3 5 7 2 7 1 6 5 0]
 [0 3 1 9 9 6 6 7 8]
 [8 7 0 8 6 8 9 8 3]
 [6 1 7 4 9 2 0 8 2]
 [7 8 4 4 1 7 6 9 4]
 [1 5 9 7 1 3 5 7 3]
 [6 6 7 9 1 9 6 0 3]
 [8 4 1 4 5 0 3 1 4]
 [4 4 0 0 8 4 6 9 3]]
