In [41]:
import numpy as np
import time


In [42]:
# _____________________ sudoku checker

def sub_box(ar, i, j):
    a = list(ar[i * 3:i * 3 + 3, j * 3:j * 3 + 3].flatten())
    b = check_3_ar(a)
    if b == True: return f'Box True'
    return f'Box False'

def sub_col(ar,n):
    # ar = ar[:,n]
    b = check_3_ar(ar[:,n])
    if b == True: return f'Col True'
    return f'Col False'

def sub_row(ar,n):
    # ar = ar[n,:]
    b = check_3_ar(ar[n,:])
    if b == True: return f'Row True'
    return f'Row False'

def check_3_ar(ar):
    ar = sorted(list(ar))
    a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
    return ar == a

def auto_check_9(ar):
    a = {}
    k = 0
    for i in range(3):
        for j in range(3):
            print(i, j)
            b = sub_box(ar, i, j)
            a.update({b})
            c = sub_col(ar, k)
            a.update({c})
            d = sub_row(ar, k)
            a.update({d})
            print(a)
            print(b)
            print(c)
            print(d)
            k += 1
    if b == f'Box True' and c == f'Col True' and d == f'Row True': 
        print('True')
        return True
    else: 
        print('False')
        return False

            

In [43]:
def auto_check_9(ar):
    aa = {'Col True', 'Row True', 'Box True'}
    a = set()
    k = 0
    for i in range(3):
        for j in range(3):
            print(i, j)
            b = sub_box(ar, i, j)
            a.add(b)
            c = sub_col(ar, k)
            a.add(c)
            d = sub_row(ar, k)
            a.add(d)
            print(a)
            # print(b)
            # print(c)
            # print(d)
            k += 1
    print(f'auto check 9 finished')
    if a == aa: 
        print('True')
        return True
    else: 
        print('False')
        return False

In [44]:
# _____________________ role of sudoku   

# l = 0 ; m = 0
# for k in range(9):
#     for i in range(3):
#         for j in range(3):
#             print(f'{i + m }:{j + l}')
#     l+=3
#     if l > 6: l = 0; m += 3

# 0:0 0:1 0:2 1:0 1:1 1:2 2:0 2:1 2:2
# 0:3 0:4 0:5 1:3 1:4 1:5 2:3 2:4 2:5
# 0:6 0:7 0:8 1:6 1:7 1:8 2:6 2:7 2:8
# 3:0 3:1 3:2 4:0 4:1 4:2 5:0 5:1 5:2
# 3:3 3:4 3:5 4:3 4:4 4:5 5:3 5:4 5:5
# 3:6 3:7 3:8 4:6 4:7 4:8 5:6 5:7 5:8
# 6:0 6:1 6:2 7:0 7:1 7:2 8:0 8:1 8:2
    
# pattern of check sub-box
# [0:3,0:3] [0:3,3:6] [0:3,6:9] 
# [3:6,0:3] [3:6,3:6] [3:6,6:9] 
# [6:9,0:3] [6:9,3:6] [6:9,6:9]

sb_0 = [0,0,0,3,3,3,6,6,6]
sb_1 = [3,3,3,6,6,6,9,9,9]
sb_2 = [0,3,6,0,3,6,0,3,6]
sb_3 = [3,6,9,3,6,9,3,6,9]



def possible_check(ar,i,j,k,value,allprop_list,count):
    
    print(f'checking {i} {j} {value}')
    c = {1, 2, 3, 4, 5, 6, 7, 8, 9}
    
    row_col_sub = []
    
    if value == 0: 
        # print(ar)
        subrow = set(ar[i,:])
        # print(f'subrow = {subrow}') 
        l_subrow = list(c - subrow)
        # print(f'l_subrow = {l_subrow}')
        row_col_sub.extend(l_subrow) # extend = add list to list
        
        subcol = set(ar[:,j])
        # print(f'subcol = {subcol}')
        l_subcol = list(c - subcol)
        # print(f'l_subcol = {l_subcol}')
        row_col_sub.extend(l_subcol)
        
        # subbox = set(ar[i * 3:i * 3 + 3, j * 3:j * 3 + 3].flatten())
        subbox = set(ar[sb_0[k]:sb_1[k], sb_2[k]:sb_3[k]].flatten())
        # print(f'subbox = {subbox}')
        l_subbox = list(c - subbox)
        # print(f'l_subbox = {l_subbox}')
        row_col_sub.extend(l_subbox)
        
        row_col_sub = sorted(row_col_sub)
        # print(f'rowcolsub = {row_col_sub}')
        
        # calculate weight
        rcs_s = set(row_col_sub)
        rcs_l = list(rcs_s)
        weight = [row_col_sub.count(i) for i in rcs_s]
        # print(f'allpro = {rcs_l}') # ตัวเลบที่มีโอกาศทั้งหมด
        # print(f'weight = {weight}') # นับจำนวนตัวเลขที่มีโอกาศ
        weight_cal = [round((weight[i]*10/sum(weight))/10,3) for i in range(len(weight))]
        # print(f'w_cal = {weight_cal}')
            
        a = subrow.union(subcol,subbox)
        a = c - a
        print(f'a = {a}')
        weight_a = [round(1/len(a),4) for i in range(len(a))]
        print(f'w_a = {weight_a}')
        
        
        
        # replace 0 to value
        # if len(a) == 1:
        #     ar[i,j] = list(a)[0]
        #     print(f'ar[{i},{j}] = {list(a)[0]}')
        #     print(ar)
        #     print(a)
        # else:
        allprop_list.append([ i,j,sorted(list(a)),weight_a[0]])

def replace(ar, i, j, value):
    ar[i,j] = value
    print(f'ar[{i},{j}] = {value}')
    # print(ar)
    print(f'ar[{i},{j}] = {value} finished')

def main(ar):
    arr = ar.copy()
    print(ar)
    b = 0
    
    # use
    while True:
        allprop = []
        l = 0 ; m = 0 ; a = 0
        for k in range(9):
            for i in range(3):
                for j in range(3):
                    a+=1
                    possible_check(arr, i+m, j+l, k, arr[i+m, j+l], allprop,a)
            l+=3
            if l > 6: l = 0; m += 3
            print(f'allprop t:{b} k:{k} :')
            for i in allprop:print(i)
        print()
        print('allprop finished')
        allprop_copy = allprop.copy()
        for i in range(len(allprop_copy)):
            print(f'{allprop_copy[i]}')
            if allprop_copy[i][3] == 1:
                print('yes')
                replace(arr, allprop_copy[i][0], allprop_copy[i][1], allprop_copy[i][2][0])
                allprop.remove(allprop_copy[i])
            print()
        b+=1 
        print(f'allprop final {b} :')
        for i in allprop:print(i)
        print(ar, end='\n\n')
        print(arr)
        print(f'possible_check finished {b} times')
        if b > 15 : break
        if auto_check_9(arr) : 
            print('this sudoku done!')
            break
    
    # test
    # allprop = []
    # l = 0 ; m = 0 ; a = 0
    # for k in range(9):
    #     for i in range(3):
    #         for j in range(3):
    #             a+=1
    #             possible_check(arr, i+m, j+l, k, arr[i+m, j+l], allprop,a)
    #     l+=3
    #     if l > 6: l = 0; m += 3
    #     print(f'allprop t:{b} k:{k} :')
    #     for i in allprop:print(i)
    # print()
    # print('allprop finished')
    # allprop_copy = allprop.copy()
    # for i in range(len(allprop_copy)):
    #     print(f'{i} {allprop_copy[i]}')
    #     if allprop_copy[i][3] == 1:
    #         print('yes')
    #         replace(arr, allprop_copy[i][0], allprop_copy[i][1], allprop_copy[i][2][0])
    #         allprop.remove(allprop_copy[i])
    #     print()
    # b+=1 
    # print(f'allprop final {b} :')
    # for i in allprop:print(i)
    # print(ar, end='\n\n')
    # print(arr)
    # print(f'possible_check finished {b} times')

In [45]:
# correct

array = [
    [1, 4, 5, 3, 2, 7, 6, 9, 8],
    [8, 3, 9, 6, 5, 4, 1, 2, 7],
    [6, 7, 2, 9, 1, 8, 5, 4, 3],
    [4, 9, 6, 1, 8, 5, 3, 7, 2],
    [2, 1, 8, 4, 7, 3, 9, 5, 6],
    [7, 5, 3, 2, 9, 6, 4, 8, 1],
    [3, 6, 7, 5, 4, 2, 8, 1, 9],
    [9, 8, 4, 7, 6, 1, 2, 3, 5],
    [5, 2, 1, 8, 3, 9, 7, 6, 4]
]

# test
# array = [
#     [1, 0, 0, 0, 0, 0, 0, 0, 0],
#     [0, 2, 0, 0, 0, 0, 0, 0, 0],
#     [0, 0, 0, 0, 0, 0, 0, 0, 0],
#     [4, 0, 0, 0, 0, 0, 0, 0, 0],
#     [5, 0, 0, 0, 0, 0, 0, 0, 0],
#     [6, 0, 0, 0, 0, 0, 0, 0, 0],
#     [7, 0, 0, 0, 0, 0, 0, 0, 0],
#     [8, 0, 0, 0, 0, 0, 0, 0, 0],
#     [9, 0, 0, 0, 0, 0, 0, 0, 0]
# ]

#easy
# link = https://www.mathinenglish.com/puzzlessudoku.php?pstid=605#google_vignette
easy_array_1 = [
    [1, 0, 6, 0, 7, 8, 0, 3, 0],
    [0, 5, 7, 3, 4, 9, 0, 6, 2],
    [2, 9, 3, 6, 0, 5, 0, 0, 7],
    [0, 0, 0, 8, 0, 1, 6, 0, 4],
    [4, 6, 1, 0, 0, 0, 2, 8, 9],
    [5, 8, 0, 0, 6, 4, 3, 0, 0],
    [7, 3, 4, 1, 9, 6, 5, 0, 8],
    [6, 1, 8, 7, 0, 2, 4, 9, 3],
    [0, 0, 0, 0, 8, 0, 0, 1, 0]
]
easy_array_2 = [
    [3, 0, 2, 9, 6, 4, 8, 5, 1],
    [9, 0, 4, 8, 1, 5, 0, 7, 0],
    [0, 0, 1, 3, 7, 2, 0, 9, 6],
    [0, 4, 0, 1, 0, 9, 0, 2, 8],
    [1, 0, 9, 0, 4, 6, 0, 0, 5],
    [5, 2, 0, 7, 0, 3, 0, 1, 4],
    [2, 0, 8, 6, 0, 1, 5, 4, 7],
    [4, 1, 0, 0, 3, 0, 2, 0, 0],
    [0, 0, 5, 0, 0, 7, 1, 0, 3]
]
easy_array_3 = [
    [0, 9, 8, 6, 4, 1, 0, 3, 7],
    [0, 0, 7, 8, 0, 0, 9, 4, 6],
    [0, 3, 6, 0, 0, 9, 8, 2, 0],
    [8, 5, 9, 2, 3, 6, 1, 7, 0],
    [0, 0, 0, 0, 9, 8, 3, 5, 2],
    [3, 0, 0, 1, 0, 7, 6, 9, 8],
    [0, 6, 0, 0, 1, 0, 4, 0, 5],
    [9, 0, 5, 7, 6, 4, 0, 1, 0],
    [0, 0, 4, 3, 8, 5, 0, 0, 9]
]
easy_array_4 = [
    [2, 1, 7, 0, 4, 5, 0, 3, 9],
    [0, 0, 0, 8, 0, 0, 5, 0, 1],
    [0, 0, 5, 3, 1, 2, 0, 0, 7],
    [6, 5, 1, 9, 0, 3, 7, 4, 2],
    [8, 2, 0, 5, 6, 7, 9, 0, 0],
    [0, 0, 0, 1, 2, 0, 6, 8, 5],
    [0, 7, 8, 0, 9, 6, 3, 5, 4],
    [0, 0, 2, 4, 0, 0, 1, 7, 0],
    [5, 0, 0, 7, 0, 1, 2, 9, 8]
]

easy_array_1 = np.array(easy_array_1) 
easy_array_2 = np.array(easy_array_2) 
easy_array_3 = np.array(easy_array_3)
easy_array_4 = np.array(easy_array_4)


corr = np.array(array)

# -------------------------------

bbb = np.random.randint(10, size=(9, 9))
# print(bb)

print(corr)

[[1 4 5 3 2 7 6 9 8]
 [8 3 9 6 5 4 1 2 7]
 [6 7 2 9 1 8 5 4 3]
 [4 9 6 1 8 5 3 7 2]
 [2 1 8 4 7 3 9 5 6]
 [7 5 3 2 9 6 4 8 1]
 [3 6 7 5 4 2 8 1 9]
 [9 8 4 7 6 1 2 3 5]
 [5 2 1 8 3 9 7 6 4]]


In [46]:
if __name__ == '__main__':
    start_time = time.time()
    main(easy_array_4)
    finished_time = time.time()
    print(f'time = {finished_time - start_time} sec')

[[2 1 7 0 4 5 0 3 9]
 [0 0 0 8 0 0 5 0 1]
 [0 0 5 3 1 2 0 0 7]
 [6 5 1 9 0 3 7 4 2]
 [8 2 0 5 6 7 9 0 0]
 [0 0 0 1 2 0 6 8 5]
 [0 7 8 0 9 6 3 5 4]
 [0 0 2 4 0 0 1 7 0]
 [5 0 0 7 0 1 2 9 8]]
checking 0 0 2
checking 0 1 1
checking 0 2 7
checking 1 0 0
a = {9, 3, 4}
w_a = [0.3333, 0.3333, 0.3333]
checking 1 1 0
a = {9, 3, 4, 6}
w_a = [0.25, 0.25, 0.25, 0.25]
checking 1 2 0
a = {9, 3, 4, 6}
w_a = [0.25, 0.25, 0.25, 0.25]
checking 2 0 0
a = {9, 4}
w_a = [0.5, 0.5]
checking 2 1 0
a = {8, 9, 4, 6}
w_a = [0.25, 0.25, 0.25, 0.25]
checking 2 2 5
allprop t:0 k:0 :
[1, 0, [3, 4, 9], 0.3333]
[1, 1, [3, 4, 6, 9], 0.25]
[1, 2, [3, 4, 6, 9], 0.25]
[2, 0, [4, 9], 0.5]
[2, 1, [4, 6, 8, 9], 0.25]
checking 0 3 0
a = {6}
w_a = [1.0]
checking 0 4 4
checking 0 5 5
checking 1 3 8
checking 1 4 0
a = {7}
w_a = [1.0]
checking 1 5 0
a = {9}
w_a = [1.0]
checking 2 3 3
checking 2 4 1
checking 2 5 2
allprop t:0 k:1 :
[1, 0, [3, 4, 9], 0.3333]
[1, 1, [3, 4, 6, 9], 0.25]
[1, 2, [3, 4, 6, 9], 0.25]
[2, 0, [4, 9], 0.5]
